---

repos:
  - hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
